all:
	make -C zorrom all
	make -C arm6 all
	make -C tlcs all
	make -C gameboy all
	make -C seanriddle all
	make -C z8 all
	make -C marc4 all
	make -C msp430 all
clean:
	make -C zorrom clean
	make -C arm6 clean
	make -C tlcs clean
	make -C gameboy clean
	make -C seanriddle clean
	make -C z8 clean
	make -C marc4 clean
	make -C msp430 clean

