all:
	make -C zorrom all
	make -C arm6 all
	make -C tlcs all
	make -C gameboy all
	make -C seanriddle all
	make -C z8 all
	make -C tms320c28x all
clean:
	make -C zorrom clean
	make -C arm6 clean
	make -C tlcs clean
	make -C gameboy clean
	make -C seanriddle clean
	make -C z8 clean
	make -C tms320c28x all

